<a href="https://colab.research.google.com/github/tarashagarwal/Analyzing-a-Global-Supply-Chain-Network/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
#Remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
#Exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])